---
title: "RfDS_1.3"
author: oooo12
date: 2023-12-2
format: html
---

```{r setup, include=FALSE}
library(tidyverse)
```


## 1.3 심미성 매핑 aesthetic

```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x=displ,y=hwy,color = class))
```

```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x=displ,y=hwy,size = class))
```


```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x=displ,y=hwy,alpha = class))
```

```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x=displ,y=hwy,shape = class))
```

```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x=displ,y=hwy),color = "blue")
```

### 1.3.1 연습문제

#### 1. 다음의 코드는 무엇이 문제인가 점들이 왜 파란색이 아닌가?
```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x=displ,y=hwy,color = "blue"))
```
::: {.callout-note}

color를 수동으로 설정하려면 aesthetic 바깥에 color 인수를 설정해야 한다. 즉, `aes()`바깥에 `color = "blue"` 를 사용해야 한다.

:::


#### 2. mpg는 어느 변수가 범주형인가?

```{r}
?mpg
summary(mpg)
```

::: {.callout-note}

manufacturer, model, trans, drv, fl, class

:::

#### 3. 연속형 변수 하나를 color, size, shape로 매핑하라.

```{r}
ggplot(data = mpg) + geom_point(aes(x=displ, y = cty, color = hwy))
```

```{r}
ggplot(data = mpg) + geom_point(aes(x=displ, y = cty, size = hwy))
```

```{r}
#| error: true
ggplot(data = mpg) + geom_point(aes(x=displ, y = cty, shape = hwy))
```

#### 4. 하나의 변수를 여러 심미성에 매핑하면 어떻게 되는가?

```{r}
ggplot(data = mpg) + geom_point(aes(x=displ, y = displ, color = displ, size = displ))
```

#### 5. stroke 심미성의 역할은 무엇인가?

```{r}
ggplot(data = mpg) + geom_point(aes(x=displ, y = cty, stroke = hwy))
```

```{r}
#| error: true
ggplot(data = mpg) + geom_point(aes(x=displ, y = cty, stroke = class))
```


#### 6. aes(color=displ<5)처럼 심미성을 변수 이름이 아닌 다른것에 매핑하면 어떻게 되는가?

```{r}
ggplot(data = mpg) + geom_point(aes(x=displ, y = displ, color = displ < 5, size = displ))
```

